job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: training
    CONTAINER_PREFIX: planet4-training
    WP_DB_NAME_PREFIX: planet4-training_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: training
    HELM_RELEASE: planet4-training
    WP_DB_NAME: planet4-training_wordpress_develop
    WP_STATELESS_BUCKET: planet4-training-stateless-develop
